name: open_spy_skrip_dev

networks:
  traefik_net:
    external: true

services:
  open_spy_skrip_dev:
    image: open_spy_skrip_dev:latest
    command: npm start
    restart: always
    mem_limit: 1024m
    stop_grace_period: 90s
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 30s
    env_file: .env
    ports:
      - 3000
    networks:
      - traefik_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.open_spy_skrip_dev.rule=Host(`open-spy.skrip.dev`)"
      - "traefik.http.routers.open_spy_skrip_dev.entrypoints=websecure"
      - "traefik.http.routers.open_spy_skrip_dev.tls.certresolver=letsencrypt"
      - "traefik.http.routers.open_spy_skrip_dev.tls.domains[0].main=*.skrip.dev"
