name: DEPLOY

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  production:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_FANG_URL }}
          username: ${{ secrets.DOCKER_REGISTRY_FANG_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_FANG_PASS }}

      - run: cp .env.example .env

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY_FANG_URL }}/open_spy_skrip_dev:${{ github.sha }}
